### ISSUE TITLE
how can I add a modbus write funktion

### ISSUE THREAD

**Issue by dr-ni** [s10l/deye-logger-at-cmd#3]
for example -xmbw

**Comment by belzig** [comment]
Reading the Register for  "Set Read Active Power Regulation"  works like this

eg : Power is set to  46% ~ hex 2E via pro.solarmanppv-app then the output of reads:
C:\Deye>main -t 192.168.179.17:48899 -xmb 00280001
2023/02/12 14:34:48 * Connecting :0 -> 192.168.179.17:48899...
2023/02/12 14:34:52 +ok=01030200**2E**3858
2023/02/12 14:34:53



adjusting to 70% ~ hex 4B

C:\Deye>main -t 192.168.179.17:48899 -xmb 00280001
2023/02/12 14:40:03 * Connecting :0 -> 192.168.179.17:48899...
2023/02/12 14:40:06 +ok=01030200**4B**F873
2023/02/12 14:40:07

03 is read 06 is write.

I assume you have to change the line  

prefix := "0103" // Slave ID + Function

to

prefix := "0106" // Slave ID + Function

in order to change the values of the register.
But I don`t know how to pass the values

**I really dont know if this is OK, its really just a guess. Don`t try it!!!!!!!**

e.6 75% ~4B
main -t 192.168.179.17:48899 -xmb 00284B01
or 
main -t 192.168.179.17:48899 -xmb 0028004B



I don`t have the docs for the registers, so I don`t know exactly how the registers are set.

**Comment by dr-ni** [comment]
do you think it'ts dangerous to try the values?

how did you guess thes values 00284B01 and 0028004B?

**Comment by dr-ni** [comment]
I have 100%:
```
/main -t solariumiv:48899 -xmb 00280001
2023/02/12 16:46:01 * Connecting :0 -> 192.168.2.17:48899...
2023/02/12 16:46:04 +ok=0103020064B9AF
2023/02/12 16:46:05
```

**Comment by dr-ni** [comment]
[Modbus.-.-.V118.pdf](https://github.com/s10l/deye-logger-at-cmd/files/10716536/Modbus.-.-.V118.pdf)

**Comment by belzig** [comment]
+ok=01030200**64**B9AF

Hex 64  = 100

**Comment by belzig** [comment]
That`s strange, your modbus manual states in paragraph
2.6.2 write register (function code: 0x10) 

So the line in the go - source code should be

`prefix := "0116" // Slave ID + Function`

**Comment by belzig** [comment]
> do you think it'ts dangerous to try the values?
> 
> how did you guess thes values 00284B01 and 0028004B?

0028 is the register, 4B is the value.

I really don`t know if this is OK, it`s really just a guess. Don`t try it!!!!!!!

**Comment by belzig** [comment]
The modbus call should be according to your docs like this.
<Length>+<SlaveID>+<Function>+<Starting registeraddress>+<Number of registers>+<byte count>+<Register values>
for 75% Power
8,0110002800102004B

**Comment by dr-ni** [comment]
so do you think this should be ok?

[main.go.txt](https://github.com/s10l/deye-logger-at-cmd/files/10717367/main.go.txt)

**Comment by belzig** [comment]
Hi dr-ni, good job, just a few things have to be changed

Gonzo said prefix is hex.

So the line  
prefix := "0116" // Slave ID + Function

has to be changed to 

prefix := "0110" // Slave ID + Function
-----------------------------------------------

The modbus command lenght will be 14
0028000102004B

-----
} else if fModBusW != nil && *fModBusW != "" {
		if len(*fModBusW) <14 {
			fmt.Println("xmbw needs first register address, number of registers, byte count and register value")
			fmt.Println("First register 0x0028")
			fmt.Println("Length 0x0001")
                        fmt.Println("Bytecount 0x02")
                        fmt.Println("Registervalue 0x004B")
			fmt.Println("-> 0028000102004B")
			flag.Usage()
			os.Exit(1)
		}
		handler = modBusHandlerW
	}
---------

Please check the syntax because, I don`t have a go environment.

**Comment by belzig** [comment]
I installed go on my raspi

[main.go.belzig.txt](https://github.com/s10l/deye-logger-at-cmd/files/10720400/main.go.belzig.txt)

I changed some lines in the crc computing because the string is longer
But it still doesn`t work.

pi@raspberrypi:~/mbw $ go run main.go -t 192.168.102.88:48899 -xmbw 0028000102004B
2023/02/13 09:47:15 * Connecting :0 -> 192.168.102.88:48899...
2023/02/13 09:47:18 +ok=no data

The values are unchanged.
Have to dig deeper

**Comment by s10l** [comment]
I have not checked your code, but the datagram should be structured as follows (not tested yet):

```
DATAGRAM	:= ATCMD + MODBUSLEN + SEPERATOR + MODBUSMSG + MODBUSCRC
ATCMD		:= AT+INVDATA=
MODBUSLEN	:= len(MODBUSMSG + MODBUSCRC)
MODBUSCRC	:= crc(MODBUSMSG)
SEPERATOR	:= ,
MODBUSMSG	:= SLAVE + FCODE + STARTADDR + REGSIZE + VALUELEN + VALUE
SLAVE		:= 01
FCODE		:= 10
STARTADDR	:= FFFF
REGSIZE		:= 0001
VALUELEN   	:= len(VALUE)
VALUE		:= 0000
```

len returns the size/len in bytes, eg. FFFF -> 0xFF and 0xFF -> 2 bytes

**Comment by s10l** [comment]
I can push the code with write support later. Where can I find the value for _Active power regulation_ in the UI?

**Comment by belzig** [comment]
Slave =01
FCODE =10
STARTADDR =0028
REGSIZE = 0001
Valuelenght = 02
Value = 00 4B
CRC= 4FE0

 01 10 00 28 00 01 02 00 4B 4F E0

So the MODBUSLEN  would be 11 Bytes?

SO the Line should be
tresponse := send(conn, fmt.Sprintf("AT+INVDATA=11,%s%s\n", cmd, hex.EncodeToString(crc)), 1, 5, true)

or 
tresponse := send(conn, fmt.Sprintf("AT+INVDATA=B,%s%s\n", cmd, hex.EncodeToString(crc)), 1, 5, true)

**Comment by belzig** [comment]
Solarman Business -> Plant -> Select Plant > Devices -> Microinverter -> Device Control -> Set Active Power Regulation

You need an  Installer-Account to have this option

**Comment by s10l** [comment]
Give it a try, but you'll have to build it yourself. Please read the notes in the Readme.md

**Comment by s10l** [comment]
I was able to change 0028 to some value and back to 0064. Don't know if a restart is required.

Could also be used to reset the stats in non solarman environments.

**Comment by belzig** [comment]
Hi,
just checked out your src.

Now it works great with my raspi

switch to 75%: 
go run main.go -t 192.168.179.88:48899 -xmbw 0028000102004B
switch to 46%:
 go run main.go -t 192.168.179.88:48899 -xmbw 0028000102002E

excellent job !!!

**Comment by dr-ni** [comment]
How does this tool be working for you?
For me it's writing correct - even stored after reboot - but with modbus read
https://github.com/dr-ni/123solar_mi600/tree/main/misc/tools/deye-logger

```
Data read from logger 192.168.2.17:48899

+--------------------------------------+--------------------------------------+
| DCVoltagePV1          :     30.7 V   | DCVoltagePV2         :      31.5 V   |
| DCCurrentPV1          :      0.0 A   | DCCurrentPV2         :       0.3 A   |
| DCPowerPV1            :      0.0 W   | DCPowerPV2           :       9.5 W   |
| DailyProductionPV1    :      0.5 kWh | DailyProductionPV2   :       1.0 kWh |
| TotalProductionPV1    :    309.8 kWh | TotalProductionPV2   :     232.6 kWh |
+--------------------------------------+--------------------------------------+
| DCVoltagePV3          :      0.0 V   | DCVoltagePV4         :       0.0 V   |
| DCCurrentPV3          :      0.0 A   | DCCurrentPV4         :       0.0 A   |
| DCPowerPV3            :      0.0 W   | DCPowerPV4           :       0.0 W   |
| DailyProductionPV3    :      0.0 kWh | DailyProductionPV4   :       0.0 kWh |
| TotalProductionPV3    :      0.0 kWh | TotalProductionPV4   :       0.0 kWh |
+--------------------------------------+--------------------------------------+
| CurrentPower          :     13.0 W   | InverterSerialNumber :     |
| YieldToday            :      1.6 kWh | InverterRatedPower   :     600.0 W   |
| TotalYield            :    565.6 kWh | NumberOfMPPTs        :         2     |
| ACVoltage1            :    239.0 V   | NumberOfPhases       :         1     |
| ACCurrent1            :      0.0 A   | LoggerSerialNumber   :     |
| ACOutputFrequency     :     50.1 Hz  | LoggerMacAddress     :   |
| ACRadiatorTemperature :     12.9 GrdC| DataTimeStamp  : 2023-02-13 17:03:27 |
+--------------------------------------+--------------------------------------+
```

InverterRatedPower is always 600 W

**Comment by belzig** [comment]
RatedPower is always the max power the inverter was built for.

You will see the effects of "Set Active Power Regulation" Register 0x0028 in  solarman with the parameter
Total AC output power

I think its not an register but a computed value 
(DCVoltage1*DCCurrent1 + DCVoltage2*DCCurrent2)*Efficency

Or in your tool:
 CurrentPower

**Comment by dr-ni** [comment]
I'll check it tomorrow if the sun is strong enough

**Comment by belzig** [comment]
[main.exe.2Rename.txt](https://github.com/s10l/deye-logger-at-cmd/files/10733878/main.exe.2Rename.txt)

**Comment by dr-ni** [comment]
I did not have enough sun to get more than 300 W today (50% setting on my bosswerk mi600)

did you already notice a power reduction?

**Comment by belzig** [comment]
My Deye Sun 300 is connected to a battery.

With main I can adjust the power from 10% to 100%.
It exactly what I needed, for my base load system
Charge the battery during the day and smooth out peak loads, and use the inverter to balance the base load at night.

**Comment by dr-ni** [comment]
sadly not working on bosswerk mi600
any success with a deye sun 600?

**Comment by belzig** [comment]
The guys from https://www.photovoltaikforum.com/thread/179529-daten-von-deye-sun-mikrowechselrichtern-abfangen/?postID=3009739#post3009739
 said it works with Sun Deye 600

**Comment by belzig** [comment]
https://raw.githubusercontent.com/schwatter/solarman_mqtt/main/Deye_SUN600G3-230-EU_Register.xlsx

https://www.photovoltaikforum.com/core/attachment/337635-deye-600w-at-kommandos-befehle-returncodes-xlsx/
